# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1jhqfFBB-wMTuXIRUB3Lzm8aiJM3pUS

RETAIL CUSTOMER SEGMENTATION USING MACHINE LEARNING
"""

